StylesPath = c3standards/config/vale/styles
# This can be suggestion, warning, or error.
MinAlertLevel = warning
Packages = Microsoft, alex
Vocab = C3

[*.c3doc.md]
BasedOnStyles = Vale, C3, Microsoft, alex

# Ignore alerts in GitHub-flavored Markdown
TokenIgnores = \[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]

# Ignore LaTeX in C3-flavored Markdown
BlockIgnores = (?s)\$\$.*?\$\$

# Use the C3.Spelling rule instead, which extends from Vale.Spelling.
Vale.Spelling = NO

# This rule results in false positives for inner types (e.g., Nested.Inner.Type).
# There is a separate C3.Spacing rule.
Microsoft.Spacing = NO

# Most of the words in this list are not profane in the context they're used at C3.
# ProfanityMaybe and ProfanityLikely are still kept on.
alex.ProfanityUnlikely = NO

# Sometimes the word "simple" is used when referring to SimpleMetrics.
alex.Condescending = warning

[formats]
c3typ = js
