---
extends: spelling
message: "Did you really mean '%s'? Check spelling and capitalization."
level: error
filters:
  - '\b[Aa]ccessors?\b'
  - '\b[Aa]ctionability\b'
  - '\b[Aa]llowlists?\b'
  - '\b[Aa]nonymization\b'
  - '\b[Aa]nonymized\b'
  - '\b[Aa]pprovers?\b'
  - '\b[Aa]rchitected\b'
  - '\b[Aa]rchitecting\b'
  - '\b[Aa]rchivers?\b'
  - '\b[Aa]uditability\b'
  - '\b[Aa]utocompletes?\b'
  - '\b[Aa]utocompleted\b'
  - '\b[Aa]utocompleting\b'
  - '\b[Aa]utogenerated\b'
  - '\b[Aa]utoloaders?\b'
  - '\b[Aa]utoloaded\b'
  - '\b[Aa]utoloading\b'
  - '\b[Aa]utoscales?\b'
  - '\b[Aa]utoscaled\b'
  - '\b[Aa]utoscaler\b'
  - '\b[Aa]utoscaling\b'
  - '\b[Bb]ackfills?\b'
  - '\b[Bb]ackfilled\b'
  - '\b[Bb]ackfilling\b'
  - '\b[Bb]ackports?\b'
  - '\b[Bb]ackported\b'
  - '\b[Bb]ackporting\b'
  - '\b[Bb]acktraces?\b'
  - '\b[Bb]acktraced\b'
  - '\b[Bb]acktracing\b'
  - '\b[Bb]adging\b'
  - '\b[Bb]lockquotes?\b'
  - '\b[Bb]lockquoted\b'
  - '\b[Bb]lockquoting\b'
  - '\b[Bb]ooleans?\b'
  - '\b[Bb]rowsable\b'
  - '\b[Bb]uildpacks?\b'
  - '\b[Bb]undlers?\b'
  - '\b[Bb]urndown\b'
  - '\b[Bb]urnup\b'
  - '\b[Bb]urstable\b'
  - '\b[Cc]acheable\b'
  - '\b[Cc]addy\b'
  - '\b[Cc]allstacks?\b'
  - '\b[Cc]amo\b'
  - '\b[Cc]anonicalized\b'
  - '\b[Cc]hai\b'
  - '\b[Cc]hangesets?\b'
  - '\b[Cc]hatbots?\b'
  - '\b[Cc]hecksums?\b'
  - '\b[Cc]hecksummed\b'
  - '\b[Cc]hecksumming\b'
  - '\b[Cc]lonable\b'
  - '\b[Cc]olocated\b'
  - '\b[Cc]olocating\b'
  - '\b[Cc]ompilable\b'
  - '\b[Cc]omposable\b'
  - '\b[Cc]onda\b'
  - '\b[Cc]onfigs?\b'
  - '\b[Cc]ron\b'
  - '\b[Cc]ronjobs?\b'
  - '\b[Cc]rons?\b'
  - '\b[Cc]rontabs?\b'
  - '\b[Cc]rosslinks?\b'
  - '\b[Cc]rosslinked\b'
  - '\b[Cc]rosslinking\b'
  - '\b[Cc]ybersecurity\b'
  - '\b[Dd]atasources?\b'
  - '\b[Dd]atetime\b'
  - '\b[Dd]ebian\b'
  - '\b[Dd]ecryptable\b'
  - '\b[Dd]eduplicates?\b'
  - '\b[Dd]eduplicated\b'
  - '\b[Dd]eduplicating\b'
  - '\b[Dd]eduplication\b'
  - '\b[Dd]eliverables?\b'
  - '\b[Dd]enormalizes?\b'
  - '\b[Dd]enormalized\b'
  - '\b[Dd]enormalizing\b'
  - '\b[Dd]enylists?\b'
  - '\b[Dd]enylisting\b'
  - '\b[Dd]eployers?\b'
  - '\b[Dd]eprovisions?\b'
  - '\b[Dd]eprovisioned\b'
  - '\b[Dd]eprovisioning\b'
  - '\b[Dd]equarantine\b'
  - '\b[Dd]equarantined\b'
  - '\b[Dd]equarantining\b'
  - '\b[Dd]isambiguates?\b'
  - '\b[Dd]iscoverability\b'
  - '\b[Dd]ismissable\b'
  - '\b[Dd]irenv\b'
  - '\b[Dd]ockerfiles?\b'
  - '\b[Dd]ockerize\b'
  - '\b[Dd]ockerized\b'
  - '\b[Dd]ockerizing\b'
  - '\b[Dd]otenv\b'
  - '\b[Dd]ownvotes?\b'
  - '\b[Dd]ownvoted\b'
  - '\b[Ee]nablement\b'
  - '\b[Ee]nqueues?\b'
  - '\b[Ee]nqueued\b'
  - '\b[Ee]nums\b'
  - '\b[Ee]val\b'
  - '\b[Ee]xpirable\b'
  - '\b[Ff]acade\b'
  - '\b[Ff]acaded\b'
  - '\b[Ff]ailovers\b'
  - '\b[Ff]ailsafe\b'
  - '\b[Ff]alsy\b'
  - '\b[Ff]astlane\b'
  - '\b[Ff]avicons?\b'
  - '\b[Ff]avorited\b'
  - '\b[Ff]irewalled\b'
  - '\b[Ff]irewalling\b'
  - '\b[Ff]ormatters?\b'
  - '\b[Ff]uzzer\b'
  - '\b[Gg]etters?\b'
  - '\b[Gg]ettext\b'
  - '\b[Gg]it\b'
  - '\b[Gg]itlabsos\b'
  - '\b[Gg]lobals\b'
  - '\b[Gg]oroutines?\b'
  - '\b[Gg]ravatar\b'
  - '\b[Gg]zip\b'
  - '\b[Hh]ardcodea?\b'
  - '\b[Hh]ardcoded\b'
  - '\b[Hh]eatmapa?\b'
  - '\b[Hh]ostnames?\b'
  - '\b[Hh]otfix\b'
  - '\b[Hh]otfixes\b'
  - '\b[Hh]otfixed\b'
  - '\b[Hh]otfixing\b'
  - '\bHTTPS?\b'
  - '\b[Hh]yperparameters?\b'
  - '\b[Ii]dempotence\b'
  - '\b[Ii]dmapper\b'
  - '\b[Ii]nclusivity\b'
  - '\b[Ii]nitializers?\b'
  - '\b[Ii]nterdependency\b'
  - '\b[Ii]nterdependencies\b'
  - '\b[Ii]nterpretability\b'
  - '\b[Ii]nterruptible\b'
  - '\b[Ii]ssuables?\b'
  - '\b[Kk]eysets?\b'
  - '\b[Kk]eyspaces?\b'
  - '\b[Kk]eytabs?\b'
  - '\b[Ll]iveness\b'
  - '\b[Ll]odash\b'
  - '\b[Ll]ogrotate\b'
  - '\b[Ll]ookaheads?\b'
  - '\b[Ll]ookbehinds?\b'
  - '\b[Ll]ookups\b'
  - '\b[Ll]oopback\b'
  - '\b[Mm]arkdown\b'
  - '\b[Mm]atchers?\b'
  - '\b[Mm]emoization\b'
  - '\b[Mm]emoizes?\b'
  - '\b[Mm]emoized\b'
  - '\b[Mm]emoizing\b'
  - '\b[Mm]ergeability\b'
  - '\b[Mm]ergeable\b'
  - '\b[Mm]iddlewares?\b'
  - '\b[Mm]isconfigurations?\b'
  - '\b[Mm]isconfigures?\b'
  - '\b[Mm]isconfigured\b'
  - '\b[Mm]isconfiguring\b'
  - '\b[Mm]ixins?\b'
  - '\b[Mm]ockups?\b'
  - '\b[Mm]onorepos?\b'
  - '\b[Mm]ultiline\b'
  - '\b[Mm]utex\b'
  - '\b[Nn]ameservers?\b'
  - '\b[Nn]amespaces?\b'
  - '\b[Nn]amespaced\b'
  - '\b[Nn]amespacings?\b'
  - '\b[Nn]egatable\b'
  - '\b[Nn]ullability\b'
  - '\b[Nn]ullable\b'
  - '\b[Oo]ffboards\b'
  - '\b[Oo]ffboarded\b'
  - '\b[Oo]ffboarding\b'
  - '\b[Oo]nboarding\b'
  - '\b[Pp]arallelizations?\b'
  - '\b[Pp]asswordless\b'
  - '\b[Pp]erformant\b'
  - '\b[Pp]ersistable\b'
  - '\b[Pp]hasers?\b'
  - '\b[Pp]hpenv\b'
  - '\b[Pp]ipenv\b'
  - '\b[Pp]laintext\b'
  - '\b[Pp]olyfills?\b'
  - '\b[Pp]ooler\b'
  - '\b[Pp]ostfixed\b'
  - '\b[Pp]recompiles?\b'
  - '\b[Pp]recompiled\b'
  - '\b[Pp]reconfigures?\b'
  - '\b[Pp]reconfigured\b'
  - '\b[Pp]refills?\b'
  - '\b[Pp]refilled\b'
  - '\b[Pp]refilling\b'
  - '\b[Pp]reloads?\b'
  - '\b[Pp]reloading\b'
  - '\b[Pp]repends?\b'
  - '\b[Pp]repended\b'
  - '\b[Pp]repending\b'
  - '\b[Pp]repopulated\b'
  - '\b[Pp]rofilers?\b'
  - '\b[Pp]rotobuf\b'
  - '\b[Pp]rotobufs\b'
  - '\b[Pp]roxied\b'
  - '\b[Pp]roxies\b'
  - '\b[Pp]roxyable\b'
  - '\b[Pp]roxying\b'
  - '\b[Pp]seudocode\b'
  - '\b[Pp]seudonymized\b'
  - '\b[Pp]seudonymizer\b'
  - '\b[Qq]ueryable\b'
  - '\b[Rr]eachability\b'
  - '\b[Rr]eauthenticates?\b'
  - '\b[Rr]eauthenticated\b'
  - '\b[Rr]eauthenticating\b'
  - '\b[Rr]ebalancing\b'
  - '\b[Rr]ebar\b'
  - '\b[Rr]ebases?\b'
  - '\b[Rr]ebased\b'
  - '\b[Rr]ebasing\b'
  - '\b[Rr]edirection\b'
  - '\b[Rr]eferers?\b'
  - '\b[Rr]eflogs?\b'
  - '\b[Rr]efspecs?\b'
  - '\b[Rr]eindex\b'
  - '\b[Rr]eindexes\b'
  - '\b[Rr]eindexed\b'
  - '\b[Rr]eindexing\b'
  - '\b[Rr]einitialize\b'
  - '\b[Rr]einitializing\b'
  - '\b[Rr]elicensing\b'
  - '\b[Rr]emediations\b'
  - '\b[Rr]eplicables\b'
  - '\b[Rr]epmgr\b'
  - '\b[Rr]epmgrd\b'
  - '\b[Rr]epurposing\b'
  - '\b[Rr]equeues?\b'
  - '\b[Rr]equeued\b'
  - '\b[Rr]esyncs?\b'
  - '\b[Rr]esynced\b'
  - '\b[Rr]esyncing\b'
  - '\b[Rr]etargets?\b'
  - '\b[Rr]etargeted\b'
  - '\b[Rr]etargeting\b'
  - '\b[Rr]eusability\b'
  - '\b[Rr]everified\b'
  - '\b[Rr]everifies\b'
  - '\b[Rr]everify\b'
  - '\b[Rr]oadmaps?\b'
  - '\b[Rr]ollouts?\b'
  - '\b[Rr]syncs?\b'
  - '\b[Rr]synced\b'
  - '\b[Rr]syncing\b'
  - '\b[Rr]ulesets?\b'
  - '\b[Rr]unbooks?\b'
  - '\b[Rr]unit\b'
  - '\b[Rr]untimes?\b'
  - '\b[Ss]andboxing\b'
  - '\b[Ss]anitization\b'
  - '\b[Ss]calers?\b'
  - '\b[Ss]catterplots?\b'
  - '\b[Ss]crollable\b'
  - '\b[Ss]erializers?\b'
  - '\b[Ss]erializing\b'
  - '\b[Ss]erverless\b'
  - '\b[Ss]harded\b'
  - '\b[Ss]harding\b'
  - '\b[Ss]kippable\b'
  - '\b[Ss]martcards?\b'
  - '\b[Ss]napshotting\b'
  - '\b[Ss]parklines?\b'
  - '\b[Ss]pidering\b'
  - '\b[Ss]tarrers?\b'
  - '\b[Ss]torable\b'
  - '\b[Ss]torages\b'
  - '\b[Ss]trace\b'
  - '\b[Ss]trikethroughs?\b'
  - '\b[Ss]tunnel\b'
  - '\b[Ss]ubcharts?\b'
  - '\b[Ss]ubcommands?\b'
  - '\b[Ss]ubfolders?\b'
  - '\b[Ss]ubgraphs?\b'
  - '\b[Ss]ubgroups?\b'
  - '\b[Ss]ubkeys?\b'
  - '\b[Ss]ublicenses?\b'
  - '\b[Ss]ublicensed\b'
  - '\b[Ss]ublicensing\b'
  - '\b[Ss]ubnets?\b'
  - '\b[Ss]ubnetting\b'
  - '\b[Ss]ubpaths?\b'
  - '\b[Ss]ubprojects?\b'
  - '\b[Ss]ubquery\b'
  - '\b[Ss]ubqueries\b'
  - '\b[Ss]ubqueried\b'
  - '\b[Ss]ubquerying\b'
  - '\b[Ss]ubstrings?\b'
  - '\b[Ss]ubtasks?\b'
  - '\b[Ss]ubtests?\b'
  - '\b[Ss]ubtrees?\b'
  - '\b[Ss]udo\b'
  - '\b[Ss]upercookies?\b'
  - '\b[Ss]upertypes?\b'
  - '\b[Ss]wappiness\b'
  - '\b[Ss]wimlanes?\b'
  - '\b[Ss]yncable\b'
  - '\b[Ss]yscalls?\b'
  - '\b[Ss]yslog\b'
  - '\b[Tt]emplated\b'
  - '\b[Tt]imebox\b'
  - '\b[Tt]imeboxed\b'
  - '\b[Tt]imeboxes\b'
  - '\b[Tt]imeboxing\b'
  - '\b[Tt]imecop\b'
  - '\b[Tt]imeseries\b'
  - '\b[Tt]odos\b'
  - '\b[Tt]okenizers?\b'
  - '\b[Tt]okenizing\b'
  - '\b[Tt]oolchains?\b'
  - '\b[Tt]oolkits?\b'
  - '\b[Tt]ooltips?\b'
  - '\b[Tt]ransactionally\b'
  - '\b[Tt]ranspiles?\b'
  - '\b[Tt]ranspiled\b'
  - '\b[Tt]ranspiling\b'
  - '\b[Tt]riaged\b'
  - '\b[Tt]riages\b'
  - '\b[Tt]riaging\b'
  - '\b[Tt]ruthy\b'
  - '\b[Uu]napplied\b'
  - '\b[Uu]napproves?\b'
  - '\b[Uu]napproved\b'
  - '\b[Uu]napproving\b'
  - '\b[Uu]narchives?\b'
  - '\b[Uu]narchived\b'
  - '\b[Uu]narchiving\b'
  - '\b[Uu]nary\b'
  - '\b[Uu]nassign\b'
  - '\b[Uu]nassigning\b'
  - '\b[Uu]nassigns\b'
  - '\b[Uu]nchecks?\b'
  - '\b[Uu]nchecked\b'
  - '\b[Uu]nchecking\b'
  - '\b[Uu]ncomments?\b'
  - '\b[Uu]ncommented\b'
  - '\b[Uu]ncommenting\b'
  - '\b[Uu]ncordon\b'
  - '\b[Uu]nencodes?\b'
  - '\b[Uu]nencoded\b'
  - '\b[Uu]nencoder\b'
  - '\b[Uu]nencrypted\b'
  - '\b[Uu]nfollows?\b'
  - '\b[Uu]nfollowed\b'
  - '\b[Uu]nindexed\b'
  - '\b[Uu]nlinks?\b'
  - '\b[Uu]nlinking\b'
  - '\b[Uu]nmappable\b'
  - '\b[Uu]nmapped\b'
  - '\b[Uu]nmergeable\b'
  - '\b[Uu]nmerged\b'
  - '\b[Uu]nmerges\b'
  - '\b[Uu]nmerging\b'
  - '\b[Uu]nmocked\b'
  - '\b[Uu]noptimizes\b'
  - '\b[Uu]noptimized\b'
  - '\b[Uu]noptimizing\b'
  - '\b[Uu]npatched\b'
  - '\b[Uu]nprioritized\b'
  - '\b[Uu]nprotects\b'
  - '\b[Uu]nprotected\b'
  - '\b[Uu]nprotecting\b'
  - '\b[Uu]nprovisions\b'
  - '\b[Uu]nprovisioned\b'
  - '\b[Uu]npublish\b'
  - '\b[Uu]npublished\b'
  - '\b[Uu]npublishes\b'
  - '\b[Uu]npublishing\b'
  - '\b[Uu]npushed\b'
  - '\b[Uu]nreferenced\b'
  - '\b[Uu]nregisters?\b'
  - '\b[Uu]nregistered\b'
  - '\b[Uu]nreplicated\b'
  - '\b[Uu]nresolves?\b'
  - '\b[Uu]nresolved\b'
  - '\b[Uu]nresolving\b'
  - '\b[Uu]nreviewed\b'
  - '\b[Uu]nsanitized\b'
  - '\b[Uu]nschedules?\b'
  - '\b[Uu]nscoped\b'
  - '\b[Uu]nshares?\b'
  - '\b[Uu]nshared\b'
  - '\b[Uu]nstages?\b'
  - '\b[Uu]nstaged\b'
  - '\b[Uu]nstaging\b'
  - '\b[Uu]nstars?\b'
  - '\b[Uu]nstarted\b'
  - '\b[Uu]nstash\b'
  - '\b[Uu]nstashed\b'
  - '\b[Uu]nstashing\b'
  - '\b[Uu]nsynced\b'
  - '\b[Uu]nsynchronized\b'
  - '\b[Uu]ntarred\b'
  - '\b[Uu]ntracked\b'
  - '\b[Uu]ntrusted\b'
  - '\b[Uu]nverified\b'
  - '\b[Uu]nverifies\b'
  - '\b[Uu]nverify\b'
  - '\b[Uu]nverifying\b'
  - '\b[Uu]pgraders?\b'
  - '\b[Uu]ploaders?\b'
  - '\b[Uu]pserts?\b'
  - '\b[Uu]pserting\b'
  - '\b[Uu]pstreams\b'
  - '\b[Uu]pvotes?\b'
  - '\b[Uu]pvoted\b'
  - '\b[Vv]alidators?\b'
  - '\b[Vv]endored\b'
  - '\b[Vv]ersionless\b'
  - '\b[Vv]iewports?\b'
  - '\b[Vv]irtualized\b'
  - '\b[Vv]irtualizing\b'
  - '\b[Ww]alkthroughs?\b'
  - '\b[Ww]ebservers?\b'
  - '\b[Ww]ebservices?\b'
  - '\b[Ww]ebsockets?\b'
  - '\b[Ww]hitepapers?\b'
  - '\b[Ww]ireframes?\b'
  - '\b[Ww]ireframed\b'
  - '\b[Ww]ireframing\b'
  - '\b[Ww]orktrees?\b'
  - '\balex\b'
